import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar"
import Heroglobe from "@/components/HeroSection-globe"
import Herogemini from "@/components/hero-gemini"
import FlipWordsDemo from "@/components/flipwords-component"
import StickyScrollRevealDemo from "@/components/stickyscroll"
import { InfiniteMovingCardsDemo } from "@/components/testimonials"
import { LampDemo } from "@/components/lamp-component";
import { SignupFormDemo } from "@/components/contact-form"
import Footer from "@/components/Footer";
import SpotlightPreview from "@/components/Spotlight-component"
import { NextUIProvider } from "@nextui-org/system";
import {Divider} from "@nextui-org/divider";
import Slider from '../components/Slider';
import {CardHoverEffectDemo} from "@/components/service-cards"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextUIProvider>
          <Navbar />
          {/* <Heroglobe/> */}
          {/* <Herogemini/> */}
          <SpotlightPreview />
          <Divider className="my-6" />
          <Slider speed={35} height={50} pauseOnHover={true} />
          <Divider className="my-6" />
          {/* <FlipWordsDemo /> */}
          <CardHoverEffectDemo/>
          {/* <StickyScrollRevealDemo /> */}
          <InfiniteMovingCardsDemo />
          <LampDemo />
          <Divider className="my-6" />
          <SignupFormDemo />
          <Divider className="my-6" />
          {children}
          <Footer />
        </NextUIProvider>
      </body>
    </html>
  );
}
